title: Taher Dhilawala
author: Taher Dhilawala
email: hello@taher.me
description: > # this means to ignore newlines until "show_exerpts:"
  Full stack web and mobile developer cum architect with **12+ years** of experience in building applications for scale,
  architecting low level and high level designs and building and mentoring software engineering teams.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Taher Dhilawala
  tagline: Full stack developer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: false # set to true to add dark mode toggle
  portfolio_image: "assets/profile.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  disqus_shortname: taher435
  # generate social links in footer
  social_links:
    # twitter: samarsault
    github:  taher435
    linkedIn: in/tahernd
    #rss: rss
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
